### ISSUE TITLE
intro to additional material 

### ISSUE THREAD

**Issue by MalikaIhle** [formal-methods-mpi/Workshop.jl#110]
https://formal-methods-mpi.github.io/Workshop.jl/stable/5_additional/intro/

could there be an intro to foundation revisited if this section is kept there just do it appears in the bullet list?

**Comment by MalikaIhle** [comment]
just FYI I ahve no idea what Automatic Differentiation means even when looking at that page - so I'm skipping it  - just noted they were the 'Main' again is the ouputs - and it's likely I wouldn't get them either (see #92)

**Comment by Maximilian-Stefan-Ernst** [comment]
Thanks for pointing this out, I will add "Foundations revisited" to the intro.
