### ISSUE TITLE
Leonie should do a test run

### ISSUE THREAD

**Issue by Maximilian-Stefan-Ernst** [formal-methods-mpi/Workshop.jl#47]
... for munich

**Comment by moritzketzer** [comment]
@aaronpeikert @Maximilian-Stefan-Ernst @LeonieHagitte whats the status on this?

**Comment by Maximilian-Stefan-Ernst** [comment]
Thanks for reminding me, @moritzketzer, but it seems I was sleeping on this... now it's too late, unfortunately.
