### ISSUE TITLE
Derivative of Log/inv is wrong

### ISSUE THREAD

**Issue by aaronpeikert** [formal-methods-mpi/Workshop.jl#68]
These are the same?  Surely this is a copy and paste error.

https://github.com/formal-methods-mpi/Workshop.jl/blob/f563618a1f0966b472b0cd13bda2ba04866943fd/docs/src/5_additional/dual.md?plain=1#L120-L121

**Comment by Maximilian-Stefan-Ernst** [comment]
Thanks for pointing this out!
