### ISSUE TITLE
Base.\tab\tab is confusing

### ISSUE THREAD

**Issue by Maximilian-Stefan-Ernst** [formal-methods-mpi/Workshop.jl#69]
Many participants were unable to complete the task of looking up the Base namespace. Also, this is not super usefull - I suggest removing it.

**Comment by MalikaIhle** [comment]
I also didn't manage at first as I forgot the dot.
maybe write:
"– for instance, 'Base.<tab><tab>' (don't forget the dot after Base), which lists all the base functions that come with a native Julia installation' (or something factually correct) - which could be useful to know
