### ISSUE TITLE
How to exit the various REPL modes?

### ISSUE THREAD

**Issue by Maximilian-Stefan-Ernst** [formal-methods-mpi/Workshop.jl#71]

**Comment by Maximilian-Stefan-Ernst** [comment]
@moritzketzer I have been asked this during the workshop. Maybe check again if it is sufficiently well explained, and if not, please make a pr.

**Comment by MalikaIhle** [comment]
Yes it would be useful, from trying out different things: from the help mode - hitting enter gets back to julia; but from the package mode it doesn't when hitting enter but when hitting backspace (which also works for getting out of the help mode)
