### ISSUE TITLE
Remove sections on outer/inner constructor

### ISSUE THREAD

**Issue by Maximilian-Stefan-Ernst** [formal-methods-mpi/Workshop.jl#75]
@aaronpeikert @moritzketzer what's your opinion on this?

**Comment by moritzketzer** [comment]
I think that learning about constructors is rather important and solidifies understanding of types / structs in julia. I would leave it in, especially because our goal is to dive deeper into software engineering and not into data processing.

**Comment by aaronpeikert** [comment]
I am unsure. I think it really depends on the example we use (#79). If the use is clear from the example, keep it in otherwise remove it.

**Comment by Maximilian-Stefan-Ernst** [comment]
I think everything @moritzketzer said is true, and I believe that it's a very important concept. One thing to keep in mind, however, is that most participants in munich probably almost exclusively write code for themselves, and probably never wrote a package - therefore I think they may not be familiar with the idea that you want to have safety constraints in place (inner constructors) or you want to have a nice user interface (outer constructors), so they may find it difficult to understand the purpose of these things, even when we explain it.

**Comment by Maximilian-Stefan-Ernst** [comment]
ATM I think my preferred solution would be to move them to an additional materials section... but as Aaron said, we should decide after we know what to do with the Pokemon example.

**Comment by MalikaIhle** [comment]
again (as mentioned in #79 ) - having worked with relational databases and field/lab assistants entering data that needed some sort of control check - I can see the use for that, but what I'm missing is how how to link all pokemons / measurements created into a database / spreadsheet. right now, each created thing is independent and not compiled into a list  (or whatever the appropriate name is, maybe a collection? I just mean a data frame (in R language))

**Comment by Maximilian-Stefan-Ernst** [comment]
@MalikaIhle There are also `DataFrames` (https://github.com/JuliaData/DataFrames.jl) in Julia, but I think that's beyond the scope of the Workshop for now.

@aaronpeikert @moritzketzer conditional on #79 we have to decide what to do here.

**Comment by moritzketzer** [comment]
I would keep it in with the animal example, e.g., safety check: cats cannot bark.

**Comment by Maximilian-Stefan-Ernst** [comment]
We decided to keep this in for the moment, as later exercises depend on this.
