### ISSUE TITLE
Rework the Pokemon example

### ISSUE THREAD

**Issue by aaronpeikert** [formal-methods-mpi/Workshop.jl#79]
I don't find the Pokemon example very instructive. I'd rather see something that is more directly useful, for example

```
julia> abstract type Color end

julia> struct RGB{T <: AbstractFloat} <: Color
       r::T
       g::T
       b::T
       end
julia> struct CMYK{T <: AbstractFloat} <: Color
       c::T
       m::T
       y::T
       k::T
       end
julia> struct HEX{T <: String} <: Color
       hex::T
       end

darkness(c::RGB) = 1-max(c.r, c.g, c.b)
darkness(c::CMYK) = c.k
```

https://www.rapidtables.com/convert/color/rgb-to-cmyk.html

Still more complicated than I'd like, but that is true for Pokemon as well if you never came in touch with Pokemon.

**Comment by aaronpeikert** [comment]
How do you dare to say: " for Colors this `darkness` function is very specific to each color type." It works literally for an infinity number of types, like `RGB{Float64}, RGB{Float32}, RGB{Float16}` :smile_cat: 

You are right of course, that having a default operation for abstract types is a very concrete use for multiple dispatch. One option would be: `darkness(::Color) = missing`

But again, I am not satisfied with Colors as an example as well. Just feels unfair to criticize something without making the effort to come up with a counter.

**Comment by aaronpeikert** [comment]
Also I like to have first single dispatch introduced, and then move on to multiple:

```
darker(l::Color, r::Color) = darkness(l) < darkness(r)
```

**Comment by MalikaIhle** [comment]
reading this thread right after reading the pokemon example https://formal-methods-mpi.github.io/Workshop.jl/stable/3_types/types/ and I understood the pokemon example while I don't know what is going on here with the color example (of course you didn't explain as good as you did for the pokemon so likely unfair to compare). for disclosure: I never directly encountered / played pokemon in any format - though I was raised in a culture where this was a common game so I knew they are meant to have some sort of powers/ characteristics.

so at the moment - I'd keep the pokemon one. BUT - I was wondering  while reading - what is an example in my reserch that would need this besides creating a video game? could this be equivalent to relational databases a bit? first I have a list of individual types, say male and female, then for female I need their ID, number of eggs laid, number of chick raised, stuff like that, and for male different characteristics? still seem more complicated than having several sheets linked through an ID. But for the field assistant perspective that enters new data, they could add new 'lines' of data by filling this 'form' (=creating a pokemon) ? Basically, I'm not sure yet what the prupose of this thing is yet - but haven't done the exercice yet

**Comment by Maximilian-Stefan-Ernst** [comment]
@MalikaIhle hopefully, the purpose becomes clear after defining the `Measurement` type and the appropriate methods... In Julia, basically everything works via multiple dispatch, so there are a lot of things you can do with it - it is kind of difficult to come up with an example that everyone finds useful, so we have Pokemon as the toy example and Measurements as the `real-world` example. The purpose of the Measurements example is to show that you can define Types and Methods to alter the behaviour of generic Julia code (in our case the code for linear regression we wrote in the earlier chapter).

@aaronpeikert @moritzketzer We should now decide whether to keep the Pokemon or not. The other examples I found are collected in https://github.com/formal-methods-mpi/Workshop.jl/blob/main/Ideas.md , maybe have a look again and tell me your opinion.

**Comment by MalikaIhle** [comment]
I really don't mind it's about pokemon, it is just hard to see (for my mind) how to use the data as they are not agregated in a dataframe. I suppose many work with excel, relational databases for their data and may have the same kind of 'mind' ?

**Comment by Maximilian-Stefan-Ernst** [comment]
Moritz and I decided that we are going to leave the Pokemon example in for the moment; if we manage to make the animal example work we will switch in the future.

However, we will explain what Pokemon are in a footnote so that everyone can follow, even if they don't know the series.

**Comment by moritzketzer** [comment]
I think we should make it more engaging, e.g., making a dropdown with some information if people do not know pokemon, explain it as a cultural phenomenon, as it was with pokemon go, or displaying some pictures of flying pokemon they might choose.
