### ISSUE TITLE
we need a licence

### ISSUE THREAD

**Issue by aaronpeikert** [formal-methods-mpi/Workshop.jl#80]

**Comment by moritzketzer** [comment]
After discussion we either choose [CCBY4](https://creativecommons.org/licenses/by/4.0/).

We thought that the requirements by CCBY4 might be too restrictive and/or annoying.

Another choice would be [CC0](https://creativecommons.org/share-your-work/public-domain/cc0/), i.e., the most permissive one.

... and add a DOI and request to be cited.

**Comment by aaronpeikert** [comment]
I love that you immediately put what was discussed in the right place! Thanks.
