### ISSUE TITLE
names of navigation links 

### ISSUE THREAD

**Issue by MalikaIhle** [formal-methods-mpi/Workshop.jl#86]
could this be e.g. 'Ch. 2 Syntax - Theory' rather than jsut 'Theory' which appears several times ?

**Comment by Maximilian-Stefan-Ernst** [comment]
The idea was to have two subchapters to each chapter; one called "theory" and one "exercise" - theory explains the concept, and exercise puts it to practice - do you think that's confusing?

**Comment by MalikaIhle** [comment]
it's only confusing in the navigator at the end of the pages 
![image](https://github.com/formal-methods-mpi/Workshop.jl/assets/16382829/6ad441c4-3388-4d4a-862a-a08ed9021cfd)

**Comment by Maximilian-Stefan-Ernst** [comment]
You are right, that's pretty confusing 😄
