### ISSUE TITLE
can't see y axis on graph

### ISSUE THREAD

**Issue by MalikaIhle** [formal-methods-mpi/Workshop.jl#89]
![image](https://github.com/formal-methods-mpi/Workshop.jl/assets/16382829/ddfabc0b-6a4d-43a9-80c2-d7aae5b53612)

**Comment by moritzketzer** [comment]
Hi @MalikaIhle,

thank you for the issue. However, I don't understand the cropped screenshot.

Can you describe your issue further and upload an uncropped image of your entire webview?

You encountered it here?

https://formal-methods-mpi.github.io/Workshop.jl/stable/2_syntax/exercise/

**Comment by MalikaIhle** [comment]
![image](https://github.com/formal-methods-mpi/Workshop.jl/assets/16382829/bc6023ea-c122-41e4-8406-50fcfd31eb7c)

**Comment by MalikaIhle** [comment]
we can't see the Y axis

**Comment by aaronpeikert** [comment]
https://github.com/jheinen/GR.jl/issues/318
