### ISSUE TITLE
output creation first pikachu - not getting the same

### ISSUE THREAD

**Issue by MalikaIhle** [formal-methods-mpi/Workshop.jl#92]
the text says:
We are now able to create our very own Pikachu to fight in our team:

my_pikachu = Pikachu("Pika", 135, 80, 110, 132)

Main.Pikachu("Pika", 135, 80, 110, 132)

as an outcome I get:
Pikachu("Pika", 135, 80, 110, 132) _without 'Main'_

**Comment by MalikaIhle** [comment]
also later:

import Random: randstring
Pikachu(attack, defense, speed, hp) = Pikachu(randstring(10), attack, defense, speed, hp)

Main.Pikachu

I don't have 'Main.'

**Comment by MalikaIhle** [comment]
also here:

So if I want to be lazy and not come up with a nickname, i just sample a random one:

my_lazy_pikachu = Pikachu(132, 34, 23, 343)

Main.Pikachu("AnglBkwKNc", 132, 34, 23, 343)

**Comment by MalikaIhle** [comment]
also here https://formal-methods-mpi.github.io/Workshop.jl/stable/4_dispatch/exercise/

Main.Measurement(3.32, 1.77)

**Comment by Maximilian-Stefan-Ernst** [comment]
I guess this is because of Documenter - maybe just add a sentence that it is expected and nothing to worry about?
