### ISSUE TITLE
2_syntax/exercise/ confusions

### ISSUE THREAD

**Issue by MalikaIhle** [formal-methods-mpi/Workshop.jl#95]
https://formal-methods-mpi.github.io/Workshop.jl/stable/2_syntax/exercise/ 
slightly confused that I don't get the same nubmers given the same seed and doing commands in same order

also, confused with y += 500*randn(20)
what does += do?

**Comment by Maximilian-Stefan-Ernst** [comment]
The random number issue is fixed in #113 .
I will add short sentence that `a += b` is the same as `a = a + b`; (this syntax does not exist in R, but in Python for example).
