### ISSUE TITLE
dispatch definition 

### ISSUE THREAD

**Issue by MalikaIhle** [formal-methods-mpi/Workshop.jl#98]
https://formal-methods-mpi.github.io/Workshop.jl/stable/4_dispatch/dispatch/

"If we multiply two numbers together, we will get their product, if we multiply two strings together, they are concatenated, and if we multiply two arrays, we get a matrix product. So functions are able to specialise on the type of the input arguments. **Every such specialisation we call a method of that function**. We can for example take a look at all the methods for "

I don't think the sentence in bold here is english - do you mean 'is called' instead of 'we call' ?
what is the definition of dispatch in relation to this text? 
could one say 'such function are then said to have multiple dispatch' ? or something? it jsut a word that is used in the title and first sentence but I don't know what it means so I was hoping to get a definition right after an example

**Comment by Maximilian-Stefan-Ernst** [comment]
Thanks, I will improve the definition.
