### ISSUE TITLE
method definition.

### ISSUE THREAD

**Issue by MalikaIhle** [formal-methods-mpi/Workshop.jl#99]
https://formal-methods-mpi.github.io/Workshop.jl/stable/4_dispatch/dispatch/

"Strg/Cmd + Left-Click on the link to directly take us to the method definition."
I suspect the shortcut here is for Mac, not windows. on windows it says I should ctrl + click but it doesn't work - nothing openes. should I get a help apge to open? a browser page?

maybe best to say one can open the link to access to the detailed method definition or something (though i don't manage to do it)

**Comment by Maximilian-Stefan-Ernst** [comment]
You are right; for some reason this only works for methods that are not in Base Julia (i.e. in packages). I will reformulate it.
